name: Build Frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - "Makefile"
      - ".github/**"
      - "app/**"
      - "plugins/**"
  push:
    branches:
      - main
      - rc-*
      - testing-rc-*
    paths:
      - "frontend/**"
      - Makefile
      - ".github/**"
      - "app/**"
      - "plugins/**"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend && bun install --frozen-lockfile

      - name: Run linter
        run: |
          cd frontend && bun run lint -- --max-warnings 0 && bun run format-check

  test:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend && bun install --frozen-lockfile

      - name: Run tests
        run: |
          cd frontend && bun test -- --coverage

      - name: Run frontend-i18n-check
        run: |
          cd frontend && bun run i18n -- --fail-on-update

  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend && bun install --frozen-lockfile

      - name: Build Frontend
        run: |
          cd frontend && bun run build

  # testplugins:
  #   name: test plugins
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #       os: [ubuntu-22.04]
  #
  #   steps:
  #     - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
  #
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: latest
  #
  #     - name: Test plugins
  #       run: |
  #         cd plugins/caravan-plugin && bun install && ./test-caravan-plugin.js && ./test-plugins-examples.sh

  builddocs:
    name: build docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend && bun install --frozen-lockfile

      - name: Build docs
        run: |
          cd frontend && bun run build-typedoc

  buildstorybook:
    name: build storybook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend && bun install --frozen-lockfile

      - name: Build storybook
        run: |
          cd frontend && bun run build-storybook
